version: '3.8'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "12345"
      POSTGRES_DB: motorrentaldb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  webapi:
    image: motorrental.webapi:latest
    build:
      context: .
      dockerfile: src/MotorRental.WebApi/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - database
      - rabbitmq

  worker:
    image: motorrental.worker:latest
    build:
      context: .
      dockerfile: src/MotorRental.Workers/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Compose
      - RabbitMQ__HostName=rabbitmq
    depends_on:
      - database
      - rabbitmq

volumes:
  postgres-data:
